services:
  - type: web
    name: dande-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    scaling:
      minInstances: 1
      maxInstances: 3
    disk:
      name: dande-disk
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1

databases:
  - name: dande-mongodb
    databaseName: dande
    user: dande_user